name: style
on: [push]
jobs:
    style:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Linting flake8
          run: flake8 .
        - name: Linting imports
          run: isort . --check
        - name: Linting code
          run: black . --check
