name: style
on: [push]
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: ['3.6', '3.7', '3.8', '3.9']
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Linting imports
          run: isort . --check
        - name: Linting code
          run: black . --check
